use std::collections::HashMap;
use std::env;
use std::fs;
use std::time;

use crate::file_names;
use crate::parse_makefile;
/// DependencySearcher is a cached file time and dependency lookup tool
///
/// DependencySearcher has two public API calls:
///
/// First, you can query if one file is newer than the other.
/// Second, you can query if a source file (or the headers it includes) are newer than the the compiled object file.
///
/// All fs calls are cached on a per-object basis to minimize sytem call overhead.
/// In all lookups, the application modification time is also considered an implicit dependency of the file.
/// Source file dependencies are calculated by parcing the dependency file generated by gcc.
pub struct DependencySearcher {
    file_times: HashMap<String, time::SystemTime>,
}
impl DependencySearcher {
    /// Create a DependencySearcher
    pub fn new() -> DependencySearcher {
        DependencySearcher {
            file_times: HashMap::new(),
        }
    }
    /// Queries the file modification time, from cache if available
    fn file_time(&mut self, path: &str) -> Option<time::SystemTime> {
        if self.file_times.contains_key(path) {
            return self.file_times.get(path).cloned();
        } else {
            match fs::metadata(path).map(|m| m.modified().unwrap()) {
                Ok(t) => {
                    self.file_times.insert(path.to_owned(), t);
                    return Some(t);
                }
                Err(_) => return None,
            }
        }
    }
    #[deprecated(note = "Unclear Function Name, use is_source_newer_than_output()")]
    pub fn is_newer(&mut self, src_file: &str, out_file: &str) -> bool {
        self.is_source_newer_than_output(out_file, src_file)
    }
    #[deprecated(note = "Unclear Function Name, use is_source_newer_than_output_list()")]
    pub fn is_newer_list<'input>(
        &mut self,
        out_file: &str,
        deps: impl IntoIterator<Item = &'input String>,
    ) -> bool {
        self.is_source_newer_than_output_list(out_file, deps)
    }
    /// Returns true if src_file is newer than out_file or out_file does not exist
    pub fn is_source_newer_than_output(&mut self, src_file: &str, out_file: &str) -> bool {
        self.is_source_newer_than_output_list(out_file, &[src_file.to_owned()])
    }
    /// Returns FALSE if the out_file is newer the all of the dependencies/sources in the list
    /// True if outfile is older, or missing, or the answer is indeterminant (missing input file)
    pub fn is_source_newer_than_output_list<'input>(
        &mut self,
        out_file: &str,
        sources: impl IntoIterator<Item = &'input String>,
    ) -> bool {
        let exe_time = self.file_time(&env::args().next().unwrap()).unwrap(); // Get time of app build
        self.file_time(&out_file)
            .map(|obj_time| {
                if exe_time > obj_time {
                    // The built build_system being newer forces a recompile.
                    true
                } else {
                    for src in sources {
                        if self
                            .file_time(&src)
                            .map(|src_time| {
                                // source is newer, duh
                                src_time > obj_time
                            })
                            // Source is missing, assume it will be created alone the way
                            .unwrap_or(true)
                        {
                            // Optimization: Early return skipping other dependencies once the answer is known.
                            return true;
                        }
                    }
                    false // No sources were newer
                }
            })
            // Output does not exist, source is defacto newer.
            .unwrap_or(true)
    }
    /// Returns true if the source file (or its dependencies) is newer that the object file it would produce
    pub fn should_recompile(
        &mut self,
        src_file: &str,
        build_dir: &str,
        key: &file_names::HasherKey,
    ) -> bool {
        match parse_makefile::parse_dependency(&file_names::get_dep_path(src_file, build_dir, key))
        {
            Some((obj, sources)) => self.is_source_newer_than_output_list(&obj, &sources),
            None => true,
        }
    }
}
