[package]
name = "mspm0"
version = "0.1.0"
authors = ["Alex Ferro <alexferro@aereldesign.com>"]
edition = "2018"

[[bin]]
name = "makefile"
path = "makefile.rs"

[package.metadata.hammer]
type = "arm-cortex-m-gcc"

[package.metadata.hammer.tools.arm-none-eabi-gcc]
source = "tools/arm-none-eabi-gcc"
version = "10-2020-q4"

# [package.metadata.hammer.dependencies]
# build_system = "1.6.4"
# cmsis = "5.7.0"

[dependencies]
build_system = { path = ".hammer/build_system" }
cmsis = { path = ".hammer/cmsis" }
